; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Deco-Security Agent"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Deco-Security Inc."
#define MyAppURL "https://www.deco-security.com"
#define MyAppExeName "DecoSecurityAgent.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\DecoSecurity
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=DecoAgentInstaller
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Files]
Source: "..\..\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\config.py"; DestDir: "{app}"; Flags: ignoreversion
; Bundle nmap if needed
; Source: "..\..\bin\nmap.exe"; DestDir: "{app}\bin"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
; Register API Key if passed via command line to installer: /APIKEY="xyz"
Filename: "{app}\{#MyAppExeName}"; Parameters: "--api-key {code:GetApiKey}"; Flags: runhidden

; Install as Service using sc.exe
Filename: "sc.exe"; Parameters: "create DecoSecurityAgent binPath= ""{app}\{#MyAppExeName}"" start= auto displayname= ""Deco-Security Agent"""; Flags: runhidden; StatusMsg: "Registering Service..."
Filename: "sc.exe"; Parameters: "start DecoSecurityAgent"; Flags: runhidden; StatusMsg: "Starting Service..."

[UninstallRun]
Filename: "sc.exe"; Parameters: "stop DecoSecurityAgent"; Flags: runhidden
Filename: "sc.exe"; Parameters: "delete DecoSecurityAgent"; Flags: runhidden

[Code]
var
  ApiKey: String;

function GetApiKey(Param: String): String;
begin
  { Check if passed via command line /APIKEY=... }
  ApiKey := ExpandConstant('{param:APIKEY}');
  Result := ApiKey;
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
end;
