; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Deco-Security Agent"
#define MyAppVersion "2.1.0"
#define MyAppPublisher "Deco-Security Inc."
#define MyAppURL "https://deco-security.com"
#define MyAppExeName "DecoSecurityAgent.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\DecoSecurity
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=admin
OutputBaseFilename=DecoSecurityAgentInstaller
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
Name: "{commonappdata}\DecoSecurity"; Permissions: users-modify
Name: "{commonappdata}\DecoSecurity\logs"; Permissions: users-modify

[Run]
; Install the service
Filename: "{app}\{#MyAppExeName}"; Parameters: "--startup=auto install"; Flags: runhidden waituntilterminated
; Start the service
Filename: "{app}\{#MyAppExeName}"; Parameters: "start"; Flags: runhidden waituntilterminated

[UninstallRun]
; Stop the service
Filename: "{app}\{#MyAppExeName}"; Parameters: "stop"; Flags: runhidden waituntilterminated
; Remove the service
Filename: "{app}\{#MyAppExeName}"; Parameters: "remove"; Flags: runhidden waituntilterminated

[Code]
var
  OrchestratorPage: TInputQueryWizardPage;
  ApiKeyPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  OrchestratorPage := CreateInputQueryPage(wpWelcome,
    'Configuración del Servidor', 'Por favor ingrese la URL del Orchestrator',
    'Esta dirección se usará para conectar el agente.');
  OrchestratorPage.Add('Orchestrator URL:', False);
  OrchestratorPage.Values[0] := 'https://api.deco-security.com';

  ApiKeyPage := CreateInputQueryPage(OrchestratorPage.ID,
    'Autenticación', 'Por favor ingrese su API Key de Cliente',
    'Esta clave es necesaria para registrar el agente.');
  ApiKeyPage.Add('Client API Key:', False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: String;
  JsonContent: String;
  OrchestratorUrl: String;
  ApiKey: String;
begin
  if CurStep = ssPostInstall then
  begin
    OrchestratorUrl := OrchestratorPage.Values[0];
    ApiKey := ApiKeyPage.Values[0];
    
    ConfigPath := ExpandConstant('{commonappdata}\DecoSecurity\config.json');
    
    JsonContent := '{' + #13#10 +
      '    "orchestrator_url": "' + OrchestratorUrl + '",' + #13#10 +
      '    "api_key": "' + ApiKey + '"' + #13#10 +
      '}';
      
    SaveStringToFile(ConfigPath, JsonContent, False);
  end;
end;
